server:
  port: 8000

spring:
  application:
    name: HeathRecordingPlateform
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/java_sport?serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 127.0.0.1
    database: 0
    port: 6379
    password: 123456

mybatis:
  mapper-locations: mapper/*.xml
  type-aliases-package: com.google.personalhealthrecordingplateform.entity

jwt:
  tokenHeader: Authorization
  tokenHead: 'Bearer '
  secret: bingbingbing
  expiration: 1800000

