server:
  port: 8000

spring:
  application:
    name: HeathRecordingPlateform
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/java_sport?serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 127.0.0.1
    database: 0
    port: 6379
    password: 123456
  mail:
    host: smtp.163.com
    port: 465
    protocol: smtp
    username: shuobinpeng@163.com
    password: YZJYGFWZQRGVQCHD
    properties:
      mail:
        smtp:
          auth: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
            fallback: false
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000


mybatis:
  mapper-locations: mapper/*.xml
  type-aliases-package: com.google.personalhealthrecordingplateform.entity

jwt:
  tokenHeader: Authorization
  tokenHead: 'Bearer '
  secret: bingbingbing
  expiration: 1800000

qiniu:
  accessKey: VjqyGJIWeKMORqLsJR-3CMSBiKTxYF25wC5CSPbc
  secretKey: adec1oMqUWZAUKPruXLwus2822HK9wMJwpTllO8J
  bucketName: healthy-plateform-images
  path: rlp9l16g7.hn-bkt.clouddn.com


